[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[all]",
    "uvicorn",
    "python-multipart",
    "python-jose[cryptography]",
    "passlib[bcrypt]",
    "motor",
    "pydantic[email]",
    "mediapipe",
    "opencv-python-headless",
    "numpy"
]
